version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - gonginx

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - gonginx
    depends_on:
      - app

networks:
  gonginx:
